receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 20s
    scrapers:
      cpu:
      memory:


exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
  sapm:
    access_token: 
    access_token_passthrough: true
    endpoint: https://ingest.us1.signalfx.com/v2/trace
    max_connections: 100
    num_workers: 8
  signalfx:
    access_token: 
    realm: us1
    api_url: https://api.us1.signalfx.com
    ingest_url: https://ingest.us1.signalfx.com
    sync_host_metadata: true

extensions:
  health_check:
  pprof:
  zpages:

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
  filter/drop_actuator:
    traces:
      span:
        - attributes["http.route"] == "/actuator/prometheus"
        - attributes["http.route"] == "/actuator/health"
  resourcedetection:
    detectors: [gcp, env, system]
    timeout: 10s
  resource:
    attributes:
    - key: service.instance.id
      from_attribute: faas.id
      action: upsert
    - key: cloud.region
      value: "asia-east1"
      action: upsert
    - key: cloud.platform
      value: "gcp_cloud_run"
      action: insert
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, filter/drop_actuator, resourcedetection]
      exporters: [sapm]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch, resourcedetection,filter/drop_actuator, resource]
      exporters: [signalfx]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [signalfx]
